"""Generated by Django 4.2.6 on 2023-10-25 18:06."""

from django.db import migrations


class Migration(migrations.Migration):
    """
    Initializing migration.

    Add fields to Filmwork: certificate, file_path.
    """

    dependencies = [
        ('movies', 'initial0001'),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
                ALTER TABLE IF EXISTS "content"."film_work"
                ADD COLUMN IF NOT EXISTS "file_path" varchar(100) NULL;
            """,
            reverse_sql="""
                ALTER TABLE IF EXISTS "content"."film_work"
                DROP COLUMN IF EXISTS "file_path";
            """,
        ),
    ]
