"""Generated by Django 4.2.6 on 2023-10-25 18:06."""

from django.db import migrations, models


class Migration(migrations.Migration):
    """
    Initializing migration.

    Add fields to Filmwork: certificate, file_path.
    """

    dependencies = [
        ('movies', 'initial0001'),
    ]

    operations = [
        migrations.AddField(
            model_name='filmwork',
            name='file_path',
            field=models.FileField(
                blank=True,
                null=True,
                upload_to='movies/',
                verbose_name='file',
            ),
        ),
    ]
