repos:
-   repo: local
    hooks:
    -   id: flake8
        name: flake8
        description: wemake-python-styleguide enforcement
        entry: flake8
        args: ["--config=setup.cfg"]
        language: python
        types: [python]

-   repo: https://github.com/PyCQA/flake8
    rev: 6.1.0
    hooks:
    -   id: flake8
        additional_dependencies: [
            flake8-blind-except,
            flake8-builtins,
            flake8-class-attributes-order,
            flake8-cognitive-complexity,
            flake8-functions,
            flake8-mutable,
            flake8-print,
            flake8-pytest,
            flake8-pytest-style,
            flake8-variables-names,
        ]
